String text_droids="Дроны", 
  text_miners = "Объекты добычи", 
  text_buildings = "Постройки", 
  text_resources = "Ресурсы", 
  text_resource = "Добыча", 
  text_storages= "Хранилища", 
  text_enviroments= "Окружение", 
  text_info= "Информация", 
  text_world = "Мир", 
  text_job = "Работа", 
  text_zone = "Зоны", 
  text_menu = "Меню", 
  text_objects = "Объекты", 
  text_name="Объект", 
  text_nikname="Наименование", 
  text_status="Состояние", 
  text_fraction="Фракция", 


  text_count_droids="Количество дронов", 

  text_free_droids="Свободные дроны", 
  text_material="Материал", 
  text_speed="Скорость", 
  text_energy="Энергия", 
  text_carrying_capacity="Грузоподьёмность", 
  text_leak="Потребление", 
  text_radius="Радиус обзора", 
  text_selected_objects="Выберите объект", 
  text_no="Нет", 

  text_production="Производит", 
  text_progress="Процесс", 
  text_productivity="Продуктивность", 
  text_in_process="(работает)", 
  text_no_place_free="(нет места для выгрузки)", 
  text_skills="Функции", 
  text_carry="Транспортировка", 
  text_maintenance="Обеспечение", 
  text_guard="Охрана", 
  text_mine="Добыча", 
  text_build="Строительство", 

  text_job_carry="Перенести", 
  text_job_maintenance="Обеспечение", 
  text_job_patrol="Патрулирование", 
  text_job_mine="Добыча ресурса", 
  text_job_support="Обслуживание", 
  text_job_build="Создание объекта", 

  text_object_miner="Буровая установка", 
  text_object_repair="Станция ТО", 
  text_object_charge="Зарядная станция", 
  text_object_wall="Стена", 
  text_object_layer="Покрытие", 
  text_object_storage="Контейнер", 
  text_object_item="Предмет", 
  text_object_block="Залежи", 
  text_object_tree="Дерево", 
  text_object_project="Проект", 
  text_object_build="Постройка", 
  text_object_actor="Дрон", 


text_reciept="Рецепт",

  text_user="Использует", 
  text_nobody="Никто", 

  text_items="Предметы", 
  text_capacity="Вместимость", 
  text_count="Количество", 
  text_stack="Макс. кол-во", 
  text_weight="Вес", 
  text_no_name="Неизвестно", 
  text_empty="Пусто", 
  text_res_steel="Сталь", 
  text_res_stone="Камень", 
  text_res_wood="Древесина", 


  text_job_wait="Ожидает", 
  text_job_set="Не начата";
