String 
text_diagnostic="Диагностика",
text_cargo="Грузовой отсек",
  text_miners = "Объекты добычи", 
  text_buildings = "Постройки", 
  text_resources = "Ресурсы", 
  text_resource = "Добыча", 
  text_storages= "Хранилища", 
  text_enviroments= "Окружение", 
  text_info= "Информация", 
  text_world = "Мир", 
  text_job = "Работа", 
  text_zone = "Зоны", 
  text_menu = "Меню", 
  text_objects = "Объекты", 
  text_name="Объект", 
  text_nikname="Наименование", 
  text_status="Состояние", 
  text_fraction="Фракция", 


  text_count_droids="Количество дронов", 

  text_free_droids="Свободные дроны", 
  text_material="Материал", 
  text_speed="Скорость", 
  text_energy="Энергия", 
  text_carrying_capacity="Грузоподьёмность", 
  text_leak="Потребление", 
  text_radius="Радиус обзора", 
  text_selected_objects="Выберите объект", 
  text_no="нет", 
   text_yes="да", 

  //text_production="Производит", 

  text_progress="Процесс", 
  text_productivity="Продуктивность", 
  text_recources="Ресурсы",
  text_product="Продукт",
  text_in_process="(работает)", 
  text_no_place_free="(нет места для выгрузки)", 
  text_no_resources="(нет ресурсов)", 
   text_no_components="(нет хватает компонентов)", 
  text_no_request="(добыча невозможна)", 
  text_skills="Функции", 
  text_carry="транспортировка", 
  text_maintenance="обеспечение", 
  text_guard="охрана", 
  text_mine="добыча", 
  text_build="строительство", 

  text_job_carry="перенести", 
  text_job_maintenance="обеспечение", 
  text_job_patrol="патрулирование", 
  text_job_mine="добыча ресурса", 
  text_job_support="обслуживание", 
  text_job_build="создание объекта", 
  
  text_worker_move="перемещается в",
  text_worker_put="погружает",
  text_worker_get="выгружает",
  text_worker_support_charge="заряжает аккумулятор",
  text_worker_support_repair="проходит ТО",
  text_worker_repair="ремонтирует",
  text_worker_build="строит",

  text_object_drill="бур", 
  text_object_well="скважина",
  text_object_repair="станция ТО", 
  text_object_charge="зарядная станция", 
  text_object_wall="стена", 
  text_object_layer="покрытие", 
  text_object_storage="контейнер", 
  text_object_item="Предмет", 
  text_object_block="залежи", 
  text_object_tree="дерево", 
  text_object_project="проект", 
  text_object_build="постройка", 
  text_object_actor="дрон", 
    text_object_fabrica="фабрика",


text_reciept="Рецепт",

  text_user="Использует", 
  text_nobody="никто", 

  text_items="Предметы", 
  text_allow="Разрешено",
  text_capacity="Вместимость", 
  text_count="Количество", 
  text_stack="Макс. кол-во", 
  text_weight="Вес", 
  text_no_name="Неизвестно", 
  text_empty="пусто", 
  text_item_steel="руда железная", 
  text_item_stone="камень", 
  text_item_wood="древесина", 
  text_item_copper="руда медная",
  text_item_oil="нефть",
  text_item_plate_steel="лист стальной",
   text_item_plate_copper="лист медный",
text_item_rubber="каучук",

  text_job_wait="Ожидает", 
  text_job_set="Не начата";
